"""Initial CRM schema

Revision ID: 506d536ceea5
Revises: 
Create Date: 2026-07-13 05:27:10.128424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506d536ceea5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('bin', sa.String(length=20), nullable=True),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bin')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_company_name'), ['company_name'], unique=False)

    op.create_table('seo_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_key', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.String(length=320), nullable=False),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('canonical_url', sa.String(length=500), nullable=True),
    sa.Column('og_image', sa.String(length=500), nullable=True),
    sa.Column('robots', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seo_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seo_settings_page_key'), ['page_key'], unique=True)

    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('origin', sa.String(length=160), nullable=False),
    sa.Column('destination', sa.String(length=160), nullable=False),
    sa.Column('service_type', sa.Enum('GROUPAGE', 'AUTO', 'AIR', name='servicetype', native_enum=False), nullable=False),
    sa.Column('price_per_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('volumetric_factor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rounding_step', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_days_min', sa.Integer(), nullable=False),
    sa.Column('delivery_days_max', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tariffs_destination'), ['destination'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariffs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariffs_origin'), ['origin'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariffs_service_type'), ['service_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'LOGISTICIAN', name='role', native_enum=False), nullable=False),
    sa.Column('is_active_user', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('contact_name', sa.String(length=160), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('origin', sa.String(length=160), nullable=True),
    sa.Column('destination', sa.String(length=160), nullable=True),
    sa.Column('cargo_name', sa.String(length=200), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('volume_m3', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('service_type', sa.Enum('GROUPAGE', 'AUTO', 'AIR', name='servicetype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CALCULATION', 'APPROVAL', 'IN_WORK', 'COMPLETED', 'CANCELLED', name='applicationstatus', native_enum=False), nullable=False),
    sa.Column('estimated_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_manager_id'), ['manager_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=40), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=160), nullable=False),
    sa.Column('destination', sa.String(length=160), nullable=False),
    sa.Column('cargo_name', sa.String(length=200), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('volume_m3', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'LOADING', 'IN_TRANSIT', 'DELIVERED', 'DELAYED', 'CANCELLED', name='shipmentstatus', native_enum=False), nullable=False),
    sa.Column('current_location', sa.String(length=200), nullable=True),
    sa.Column('driver_name', sa.String(length=160), nullable=True),
    sa.Column('vehicle_number', sa.String(length=40), nullable=True),
    sa.Column('estimated_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_tracking_number'), ['tracking_number'], unique=True)

    op.create_table('tracking_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'LOADING', 'IN_TRANSIT', 'DELIVERED', 'DELAYED', 'CANCELLED', name='shipmentstatus', native_enum=False), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracking_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracking_events_shipment_id'), ['shipment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracking_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracking_events_shipment_id'))

    op.drop_table('tracking_events')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_tracking_number'))
        batch_op.drop_index(batch_op.f('ix_shipments_status'))
        batch_op.drop_index(batch_op.f('ix_shipments_client_id'))

    op.drop_table('shipments')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_number'))
        batch_op.drop_index(batch_op.f('ix_applications_manager_id'))
        batch_op.drop_index(batch_op.f('ix_applications_client_id'))

    op.drop_table('applications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tariffs_service_type'))
        batch_op.drop_index(batch_op.f('ix_tariffs_origin'))
        batch_op.drop_index(batch_op.f('ix_tariffs_is_active'))
        batch_op.drop_index(batch_op.f('ix_tariffs_destination'))

    op.drop_table('tariffs')
    with op.batch_alter_table('seo_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seo_settings_page_key'))

    op.drop_table('seo_settings')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_company_name'))

    op.drop_table('clients')
    # ### end Alembic commands ###
