"""Add company, official tariffs and proposal data

Revision ID: edfb09d6e51e
Revises: 506d536ceea5
Create Date: 2026-07-13 06:21:47.056830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edfb09d6e51e'
down_revision = '506d536ceea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=200), nullable=False),
    sa.Column('specifications', sa.String(length=300), nullable=True),
    sa.Column('unit', sa.String(length=80), nullable=False),
    sa.Column('minimum_units', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_included', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    with op.batch_alter_table('city_tariffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_city_tariffs_is_active'), ['is_active'], unique=False)

    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=250), nullable=False),
    sa.Column('brand_name', sa.String(length=120), nullable=False),
    sa.Column('bin', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=350), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('website', sa.String(length=250), nullable=False),
    sa.Column('director_name', sa.String(length=200), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('proposal_title', sa.String(length=250), nullable=False),
    sa.Column('proposal_intro', sa.Text(), nullable=False),
    sa.Column('vat_note', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance_km', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price_per_m3', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('full_truck_price', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('vat_included', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('vat_included')
        batch_op.drop_column('full_truck_price')
        batch_op.drop_column('price_per_m3')
        batch_op.drop_column('distance_km')

    op.drop_table('company_settings')
    with op.batch_alter_table('city_tariffs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_city_tariffs_is_active'))

    op.drop_table('city_tariffs')
    # ### end Alembic commands ###
